### ISSUE TITLE
Unable to parse github PR patch files

### ISSUE THREAD

**Issue by MabezDev** [itmettkeDE/cargo-patch#30]
I downloaded https://patch-diff.githubusercontent.com/raw/esp-rs/esp-idf-svc/pull/82.patch and am trying to apply the patch, but patching fails.

```
$ cargo patch
Error: Unable to parse patch file
```

The patch file looks like a standard git diff patch, so I see no reason why it shouldn't work?

**Comment by MabezDev** [comment]
also, looking a bit closer, the patch file is definitely relative the crate, see the original crate here: https://github.com/esp-rs/esp-idf-svc

**Comment by mettke** [comment]
Unfortunately this is a bit harder to fix then expected. 

Most important thing is that you cannot use the git patch url. You have to use the .diff url like this one: https://patch-diff.githubusercontent.com/raw/esp-rs/esp-idf-svc/pull/82.diff. Reason for this is that the git patch format is different from the standard patch format. But even that format does not work as is as it has a `a/` and `b/` attached to files which then of course do not exist, which is another difference to the diff command. Normally I recommend changing the file to make it compatible to the patch library I'm using (which is compatible with the diff command).

Unfortunately, it turned out that it is not enough to just correct these changes, as the currently logic does not allow adding or deleting files. So further changes are necessary before this particular patch file can work. 

I do not have the time to perform the changes at the moment, so either someone else may have a look at it or I will do it once I h ave a bit more spare time.
